<html>
<head>
<style type='text/css'>
body{color: black;}
.part{margin-top: 20px; width: 500px; font-weight: bold; background: #eee;}
#mergestat{margin-top: 20px;}
.error{color: red;}
.failed{color: red;}
.pass{color: blue;}
</style>
</head>
<body>
<h3>CoSim Nightly Script</h3>
host: zch66cosimbld11<br/>
  os: Linux<br/>
view: hzcosim_ncs_5.0_part2<br/>
<br/>
Results of compilation:<br/>
--------------------------<br/>
All build logs are in /tmp/ncslog/sm/WMX-AP_R5.0_BLD-1.20.01/buildlog<br/>
Generate ISL...IGNORED<br/>
Buiding SM...IGNORED<br/>
Buiding Test...IGNORED<br/>
<br/>
Results of test execution:<br/>
--------------------------<br/>
All test logs are in /tmp/ncslog/sm/WMX-AP_R5.0_BLD-1.20.01/testlog<br/>
Summary:<br/>
total - 332<br/>
passed - <span class='pass'>249</span><br/>
failed - <span class='failed'>82</span><br/>
error - <span class='error'>1</span><br/>
pass rate in the log - 75.00%<br/>
<br/>
Particulars:<br/>
Test Case 8000... <span class='pass'>PASS</span> <br/>
Test Case 8001... <span class='pass'>PASS</span> <br/>
Test Case 8002... <span class='pass'>PASS</span> <br/>
Test Case 8003... <span class='pass'>PASS</span> <br/>
Test Case 8004... <span class='pass'>PASS</span> <br/>
Test Case 8005... <span class='pass'>PASS</span> <br/>
Test Case 8006... <span class='pass'>PASS</span> <br/>
Test Case 8007... <span class='pass'>PASS</span> <br/>
Test Case 8008... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 8009... <span class='pass'>PASS</span> <br/>
Test Case 8010... <span class='pass'>PASS</span> <br/>
Test Case 8011... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 8012... <span class='pass'>PASS</span> <br/>
Test Case 8013... <span class='pass'>PASS</span> <br/>
Test Case 8014... <span class='pass'>PASS</span> <br/>
Test Case 8015... <span class='pass'>PASS</span> <br/>
Test Case 8016... <span class='pass'>PASS</span> <br/>
Test Case 8017... <span class='pass'>PASS</span> <br/>
Test Case 8018... <span class='pass'>PASS</span> <br/>
Test Case 8019... <span class='pass'>PASS</span> <br/>
Test Case 8020... <span class='pass'>PASS</span> <br/>
Test Case 8021... <span class='pass'>PASS</span> <br/>
Test Case 8022... <span class='pass'>PASS</span> <br/>
Test Case 8023... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 8024... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 8025... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 8026... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 8027... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 8028... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 8029... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 8030... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 8031... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 8032... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20001... <span class='pass'>PASS</span> <br/>
Test Case 20002... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20003... <span class='pass'>PASS</span> <br/>
Test Case 20004... <span class='pass'>PASS</span> <br/>
Test Case 20005... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20006... <span class='pass'>PASS</span> <br/>
Test Case 20007... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20008... <span class='pass'>PASS</span> <br/>
Test Case 20009... <span class='pass'>PASS</span> <br/>
Test Case 20010... <span class='pass'>PASS</span> <br/>
Test Case 20011... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20030... <span class='pass'>PASS</span> <br/>
Test Case 20031... <span class='pass'>PASS</span> <br/>
Test Case 20032... <span class='pass'>PASS</span> <br/>
Test Case 20100... <span class='pass'>PASS</span> <br/>
Test Case 20101... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20102... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20103... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20104... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20105... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20106... <span class='pass'>PASS</span> <br/>
Test Case 20107... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20108... <span class='pass'>PASS</span> <br/>
Test Case 20109... <span class='pass'>PASS</span> <br/>
Test Case 20110... <span class='pass'>PASS</span> <br/>
Test Case 20012... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20137... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20148... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20149... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20151... <span class='pass'>PASS</span> <br/>
Test Case 20152... <span class='pass'>PASS</span> <br/>
Test Case 20153... <span class='pass'>PASS</span> <br/>
Test Case 20154... <span class='pass'>PASS</span> <br/>
Test Case 20172... <span class='pass'>PASS</span> <br/>
Test Case 20173... <span class='pass'>PASS</span> <br/>
Test Case 20174... <span class='pass'>PASS</span> <br/>
Test Case 20179... <span class='pass'>PASS</span> <br/>
Test Case 20180... <span class='pass'>PASS</span> <br/>
Test Case 20181... <span class='pass'>PASS</span> <br/>
Test Case 20182... <span class='pass'>PASS</span> <br/>
Test Case 20183... <span class='pass'>PASS</span> <br/>
Test Case 20184... <span class='pass'>PASS</span> <br/>
Test Case 20185... <span class='pass'>PASS</span> <br/>
Test Case 20186... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20187... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20188... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20060... <span class='pass'>PASS</span> <br/>
Test Case 20112... <span class='pass'>PASS</span> <br/>
Test Case 20113... <span class='pass'>PASS</span> <br/>
Test Case 20114... <span class='pass'>PASS</span> <br/>
Test Case 20115... <span class='pass'>PASS</span> <br/>
Test Case 20116... <span class='pass'>PASS</span> <br/>
Test Case 20155... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20176... <span class='pass'>PASS</span> <br/>
Test Case 20020... <span class='pass'>PASS</span> <br/>
Test Case 20022... <span class='pass'>PASS</span> <br/>
Test Case 20024... <span class='pass'>PASS</span> <br/>
Test Case 20040... <span class='pass'>PASS</span> <br/>
Test Case 20041... <span class='pass'>PASS</span> <br/>
Test Case 20042... <span class='pass'>PASS</span> <br/>
Test Case 20048... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20207... <span class='pass'>PASS</span> <br/>
Test Case 20208... <span class='pass'>PASS</span> <br/>
Test Case 20209... <span class='pass'>PASS</span> <br/>
Test Case 20210... <span class='pass'>PASS</span> <br/>
Test Case 20211... <span class='pass'>PASS</span> <br/>
Test Case 20212... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20213... <span class='pass'>PASS</span> <br/>
Test Case 20214... <span class='pass'>PASS</span> <br/>
Test Case 20215... <span class='pass'>PASS</span> <br/>
Test Case 20216... <span class='pass'>PASS</span> <br/>
Test Case 20217... <span class='pass'>PASS</span> <br/>
Test Case 20218... <span class='pass'>PASS</span> <br/>
Test Case 20219... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20224... <span class='pass'>PASS</span> <br/>
Test Case 20225... <span class='pass'>PASS</span> <br/>
Test Case 20226... <span class='pass'>PASS</span> <br/>
Test Case 20227... <span class='pass'>PASS</span> <br/>
Test Case 20228... <span class='pass'>PASS</span> <br/>
Test Case 20229... <span class='pass'>PASS</span> <br/>
Test Case 20230... <span class='pass'>PASS</span> <br/>
Test Case 20231... <span class='pass'>PASS</span> <br/>
Test Case 20233... <span class='pass'>PASS</span> <br/>
Test Case 20234... <span class='pass'>PASS</span> <br/>
Test Case 20235... <span class='pass'>PASS</span> <br/>
Test Case 20236... <span class='pass'>PASS</span> <br/>
Test Case 20237... <span class='pass'>PASS</span> <br/>
Test Case 20239... <span class='pass'>PASS</span> <br/>
Test Case 20240... <span class='pass'>PASS</span> <br/>
Test Case 20241... <span class='pass'>PASS</span> <br/>
Test Case 20242... <span class='pass'>PASS</span> <br/>
Test Case 20026... <span class='pass'>PASS</span> <br/>
Test Case 20027... <span class='pass'>PASS</span> <br/>
Test Case 20120... <span class='pass'>PASS</span> <br/>
Test Case 20123... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20124... <span class='pass'>PASS</span> <br/>
Test Case 20125... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20126... <span class='pass'>PASS</span> <br/>
Test Case 20127... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20128... <span class='pass'>PASS</span> <br/>
Test Case 20129... <span class='pass'>PASS</span> <br/>
Test Case 20130... <span class='pass'>PASS</span> <br/>
Test Case 20131... <span class='pass'>PASS</span> <br/>
Test Case 20132... <span class='pass'>PASS</span> <br/>
Test Case 20133... <span class='pass'>PASS</span> <br/>
Test Case 20134... <span class='pass'>PASS</span> <br/>
Test Case 20135... <span class='pass'>PASS</span> <br/>
Test Case 20136... <span class='pass'>PASS</span> <br/>
Test Case 20028... <span class='pass'>PASS</span> <br/>
Test Case 20252... <span class='pass'>PASS</span> <br/>
Test Case 20253... <span class='pass'>PASS</span> <br/>
Test Case 20254... <span class='pass'>PASS</span> <br/>
Test Case 20255... <span class='pass'>PASS</span> <br/>
Test Case 20256... <span class='pass'>PASS</span> <br/>
Test Case 20257... <span class='pass'>PASS</span> <br/>
Test Case 20258... <span class='pass'>PASS</span> <br/>
Test Case 20259... <span class='pass'>PASS</span> <br/>
Test Case 20260... <span class='pass'>PASS</span> <br/>
Test Case 20261... <span class='pass'>PASS</span> <br/>
Test Case 20262... <span class='pass'>PASS</span> <br/>
Test Case 20263... <span class='pass'>PASS</span> <br/>
Test Case 20264... <span class='pass'>PASS</span> <br/>
Test Case 20265... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20266... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20267... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20268... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20269... <span class='pass'>PASS</span> <br/>
Test Case 20270... <span class='pass'>PASS</span> <br/>
Test Case 20272... <span class='pass'>PASS</span> <br/>
Test Case 20273... <span class='pass'>PASS</span> <br/>
Test Case 20138... <span class='pass'>PASS</span> <br/>
Test Case 20139... <span class='pass'>PASS</span> <br/>
Test Case 20140... <span class='pass'>PASS</span> <br/>
Test Case 20141... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20142... <span class='pass'>PASS</span> <br/>
Test Case 20143... <span class='pass'>PASS</span> <br/>
Test Case 20144... <span class='error'>UML Error</span> New failed case, need to be analyzed<br/>
Test Case 20145... <span class='pass'>PASS</span> <br/>
Test Case 20146... <span class='pass'>PASS</span> <br/>
Test Case 20147... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20164... <span class='pass'>PASS</span> <br/>
Test Case 20166... <span class='pass'>PASS</span> <br/>
Test Case 20167... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20168... <span class='pass'>PASS</span> <br/>
Test Case 20169... <span class='pass'>PASS</span> <br/>
Test Case 20170... <span class='pass'>PASS</span> <br/>
Test Case 20171... <span class='pass'>PASS</span> <br/>
Test Case 20274... <span class='pass'>PASS</span> <br/>
Test Case 20021... <span class='pass'>PASS</span> <br/>
Test Case 20023... <span class='pass'>PASS</span> <br/>
Test Case 20025... <span class='pass'>PASS</span> <br/>
Test Case 20200... <span class='pass'>PASS</span> <br/>
Test Case 20201... <span class='pass'>PASS</span> <br/>
Test Case 20202... <span class='pass'>PASS</span> <br/>
Test Case 20203... <span class='pass'>PASS</span> <br/>
Test Case 20204... <span class='pass'>PASS</span> <br/>
Test Case 20205... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20206... <span class='pass'>PASS</span> <br/>
Test Case 20315... <span class='pass'>PASS</span> <br/>
Test Case 20316... <span class='pass'>PASS</span> <br/>
Test Case 20317... <span class='pass'>PASS</span> <br/>
Test Case 20318... <span class='pass'>PASS</span> <br/>
Test Case 20220... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20221... <span class='pass'>PASS</span> <br/>
Test Case 20222... <span class='pass'>PASS</span> <br/>
Test Case 20223... <span class='pass'>PASS</span> <br/>
Test Case 20319... <span class='pass'>PASS</span> <br/>
Test Case 20247... <span class='pass'>PASS</span> <br/>
Test Case 20248... <span class='pass'>PASS</span> <br/>
Test Case 20249... <span class='pass'>PASS</span> <br/>
Test Case 20250... <span class='pass'>PASS</span> <br/>
Test Case 20251... <span class='pass'>PASS</span> <br/>
Test Case 20320... <span class='pass'>PASS</span> <br/>
Test Case 20321... <span class='pass'>PASS</span> <br/>
Test Case 20322... <span class='pass'>PASS</span> <br/>
Test Case 20323... <span class='pass'>PASS</span> <br/>
Test Case 20324... <span class='pass'>PASS</span> <br/>
Test Case 20325... <span class='pass'>PASS</span> <br/>
Test Case 20326... <span class='pass'>PASS</span> <br/>
Test Case 20327... <span class='pass'>PASS</span> <br/>
Test Case 20043... <span class='pass'>PASS</span> <br/>
Test Case 20044... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20045... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20046... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20047... <span class='pass'>PASS</span> <br/>
Test Case 20049... <span class='pass'>PASS</span> <br/>
Test Case 20336... <span class='pass'>PASS</span> <br/>
Test Case 20337... <span class='pass'>PASS</span> <br/>
Test Case 20338... <span class='pass'>PASS</span> <br/>
Test Case 20339... <span class='pass'>PASS</span> <br/>
Test Case 20340... <span class='pass'>PASS</span> <br/>
Test Case 20341... <span class='pass'>PASS</span> <br/>
Test Case 20342... <span class='pass'>PASS</span> <br/>
Test Case 20343... <span class='pass'>PASS</span> <br/>
Test Case 20344... <span class='pass'>PASS</span> <br/>
Test Case 20345... <span class='pass'>PASS</span> <br/>
Test Case 20346... <span class='pass'>PASS</span> <br/>
Test Case 20347... <span class='pass'>PASS</span> <br/>
Test Case 20300... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20301... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20302... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20331... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20332... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20303... <span class='pass'>PASS</span> <br/>
Test Case 20304... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20305... <span class='pass'>PASS</span> <br/>
Test Case 20306... <span class='pass'>PASS</span> <br/>
Test Case 20307... <span class='pass'>PASS</span> <br/>
Test Case 20308... <span class='pass'>PASS</span> <br/>
Test Case 20309... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20310... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20312... <span class='pass'>PASS</span> <br/>
Test Case 20330... <span class='pass'>PASS</span> <br/>
Test Case 20333... <span class='pass'>PASS</span> <br/>
Test Case 20334... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20335... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20190... <span class='pass'>PASS</span> <br/>
Test Case 20191... <span class='pass'>PASS</span> <br/>
Test Case 20280... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20281... <span class='pass'>PASS</span> <br/>
Test Case 20313... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20314... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20348... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20349... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20350... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20351... <span class='pass'>PASS</span> <br/>
Test Case 20352... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20355... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20356... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 20357... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 551001... <span class='pass'>PASS</span> <br/>
Test Case 51002... <span class='pass'>PASS</span> <br/>
Test Case 51003... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 51004... <span class='pass'>PASS</span> <br/>
Test Case 51005... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 51006... <span class='pass'>PASS</span> <br/>
Test Case 51007... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 51008... <span class='pass'>PASS</span> <br/>
Test Case 51009... <span class='pass'>PASS</span> <br/>
Test Case 51010... <span class='pass'>PASS</span> <br/>
Test Case 51011... <span class='pass'>PASS</span> <br/>
Test Case 51012... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 51013... <span class='pass'>PASS</span> <br/>
Test Case 51014... <span class='pass'>PASS</span> <br/>
Test Case 51015... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 60001... <span class='pass'>PASS</span> <br/>
Test Case 60002... <span class='pass'>PASS</span> <br/>
Test Case 60003... <span class='pass'>PASS</span> <br/>
Test Case 60004... <span class='pass'>PASS</span> <br/>
Test Case 60005... <span class='pass'>PASS</span> <br/>
Test Case 60006... <span class='pass'>PASS</span> <br/>
Test Case 60007... <span class='pass'>PASS</span> <br/>
Test Case 60008... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 60009... <span class='pass'>PASS</span> <br/>
Test Case 60010... <span class='pass'>PASS</span> <br/>
Test Case 60011... <span class='pass'>PASS</span> <br/>
Test Case 60012... <span class='pass'>PASS</span> <br/>
Test Case 60013... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 60014... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 60015... <span class='pass'>PASS</span> <br/>
Test Case 60016... <span class='pass'>PASS</span> <br/>
Test Case 20061... <span class='pass'>PASS</span> <br/>
Test Case 20062... <span class='pass'>PASS</span> <br/>
Test Case 70001... <span class='pass'>PASS</span> <br/>
Test Case 70002... <span class='pass'>PASS</span> <br/>
Test Case 70003... <span class='pass'>PASS</span> <br/>
Test Case 70005... <span class='pass'>PASS</span> <br/>
Test Case 70006... <span class='pass'>PASS</span> <br/>
Test Case 70008... <span class='pass'>PASS</span> <br/>
Test Case 70009... <span class='pass'>PASS</span> <br/>
Test Case 70010... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 70011... <span class='pass'>PASS</span> <br/>
Test Case 70012... <span class='pass'>PASS</span> <br/>
Test Case 70013... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 70014... <span class='pass'>PASS</span> <br/>
Test Case 70015... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 70016... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 70017... <span class='pass'>PASS</span> <br/>
Test Case 70018... <span class='pass'>PASS</span> <br/>
Test Case 70019... <span class='pass'>PASS</span> <br/>
Test Case 70020... <span class='pass'>PASS</span> <br/>
Test Case 70021... <span class='pass'>PASS</span> <br/>
Test Case 70022... <span class='pass'>PASS</span> <br/>
Test Case 70023... <span class='pass'>PASS</span> <br/>
Test Case 70024... <span class='pass'>PASS</span> <br/>
Test Case 70025... <span class='pass'>PASS</span> <br/>
Test Case 70026... <span class='pass'>PASS</span> <br/>
Test Case 70027... <span class='pass'>PASS</span> <br/>
Test Case 70028... <span class='pass'>PASS</span> <br/>
Test Case 70029... <span class='pass'>PASS</span> <br/>
Test Case 70030... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 70031... <span class='failed'>FAILED</span> New failed case, need to be analyzed<br/>
Test Case 70032... <span class='pass'>PASS</span> <br/>
Test Case 70033... <span class='pass'>PASS</span> <br/>
Test Case 70034... <span class='pass'>PASS</span> <br/>
Test Case 70035... <span class='pass'>PASS</span> <br/>
Test Case 70036... <span class='pass'>PASS</span> <br/>
Test Case 70037... <span class='pass'>PASS</span> <br/>
Test Case 70038... <span class='pass'>PASS</span> <br/>
<div id='mergestat'>
CRs Integrated to Baseline
<br/>
---------------------------<br/>
devint-1307106	yes	yes	SCM	Closed	bdp486~Ruiz, Luis	MOTCM01307106	MOTCM01306721	WMX5.0devint-1316290	yes	yes				MOTCM01316290			
<br/>
31	yes	yes	MAC	Closed	snaraya1~Narayanan, Sumathi	MOTCM01315431	MOTCM01254329	WMX5.0  MAC Devint Branch Creation	
<br/>
devint-1316290	yes	yes	Network_Management	Closed	cra037~Anders, Robert	MOTCM01316290	MOTCM01316288	WMX 5.0 NM Devint NM-AP_R5.0_DEVINT-1.17.00	
<br/>
r5.0_dev-1309956	yes	yes	SMA_Host_Security/IDS	Closed	dgw764~Khorkov, Anton	MOTCM01309956	MOTCM01309844	R5.0: IDS rules cleanup - SW upgrade procedure.	
<br/>
r5.0_dev-1313610	yes	yes	Platform/Kernel_Scripts/Config	Closed	cjk095~Kuzmina, Yuliya	MOTCM01313610	MOTCM01304467	Run logrotate more frequently	
<br/>
r5.0_dev-1315269	yes	yes	WiMAX_FTE_DIT/FTE_APNB_TE	Closed	r37333~Vasilchenkov, Vladimir	MOTCM01315269	MOTCM01315261	ZRU_APNB_TE: OpenR6/SpillOver Fix DHCP for automatic length/checksum calculation	
<br/>
r5.0_dev-1316710	yes	yes	Platform/Tools	Closed	wxnf68~Wei, Yanwei	MOTCM01316710	MOTCM01315593	issues with apsnap tool, logs captured by the tool, some additional improvements.	
<br/>
r5.0_dev-1317848	yes	yes	WiMAX_FTE_DIT/FTE_MAC_TE	Closed	amb110c~Beletskiy, Michael	MOTCM01317848	MOTCM01317847	ZRU_MAC_TE: Add support for DL/UL AC Metrics Ind to sch_intercept	
<br/>
r5.0_dev-1319029	yes	yes	MSM	Closed	cds130~Supehia, Dev	MOTCM01319029	MOTCM01319024	Import iSL on 5.0 Mainline for SM for WMX-MSSBTS_R5.0_RB_PATCH8	
<br/>
</div>
<div id='footer'>
Sincerely yours,
<br/>
CoSim Nightly Script
</div>
</body>
</html>
